from enum import Enum


class EpistemicState(str, Enum):
    CONFIRMED = "CONFIRMED"
    HIGHLY_LIKELY = "HIGHLY_LIKELY"
    POSSIBLE = "POSSIBLE"
    NO_EVIDENCE_FOUND = "NO_EVIDENCE_FOUND"
    INCONCLUSIVE = "INCONCLUSIVE"
    NOT_TESTED = "NOT_TESTED"
    UNSUPPORTED = "UNSUPPORTED"
    ERROR = "ERROR"


class PolicyAction(str, Enum):
    ALLOW_ORIGINAL = "ALLOW_ORIGINAL"
    ALLOW_RECONSTRUCTED_ONLY = "ALLOW_RECONSTRUCTED_ONLY"
    ALLOW_WITH_REDACTION = "ALLOW_WITH_REDACTION"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"
    QUARANTINE = "QUARANTINE"
    UNSUPPORTED = "UNSUPPORTED"


class UseProfile(str, Enum):
    ARCHIVE_ONLY = "ARCHIVE_ONLY"
    HUMAN_VIEW = "HUMAN_VIEW"
    OCR_EXTRACTION = "OCR_EXTRACTION"
    VLM_READ_ONLY = "VLM_READ_ONLY"
    RAG_INGESTION = "RAG_INGESTION"
    AGENT_WITH_TOOLS = "AGENT_WITH_TOOLS"
    SECURITY_FORENSICS = "SECURITY_FORENSICS"
    PUBLIC_REPUBLISHING = "PUBLIC_REPUBLISHING"


class ScanMode(str, Enum):
    FAST = "fast"
    DEEP = "deep"
    FORENSIC = "forensic"


class DetectorStatus(str, Enum):
    SUCCESS = "SUCCESS"
    NO_EVIDENCE = "NO_EVIDENCE"
    DETECTED = "DETECTED"
    UNSUPPORTED = "UNSUPPORTED"
    TOOL_NOT_INSTALLED = "TOOL_NOT_INSTALLED"
    TIMEOUT = "TIMEOUT"
    ERROR = "ERROR"
    NOT_TESTED = "NOT_TESTED"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    MISSING = "MISSING"
    CANCELLED = "CANCELLED"


class WatermarkState(str, Enum):
    DETECTED = "DETECTED"
    NOT_DETECTED = "NOT_DETECTED"
    INVALID_MESSAGE = "INVALID_MESSAGE"
    UNSUPPORTED = "UNSUPPORTED"
    ERROR = "ERROR"

